# Generated by Django 2.1.7 on 2019-05-22 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='todo',
            new_name='in_folder',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='parent_folder',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 24, 1, 20, 53, 397307)),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(max_length=500),
        ),
    ]
